model_path: model.conformer.conformer
dataset: smartfallmm
model_args: 
  length : 256
  channels: 3
  num_heads: 4
  num_layers: 4
  embed_dim: 16
  dropout_rate: 0.1
  attention_dropout_rate: 0.1
  mlp_dim: 32


hyperparameters:
  batch_size: 256
  epochs: 30

dataset_args: 
  directory : datasets/smartfallmm/student_participants/accelerometer/watch_accelerometer
  train_subjects: [29,31,32,36,37,40, 41, 42, 43,44,45,46]
  val_subjects: [34]
  window: 256
  stride: 10

optimizer_args: 
  # global_clipnorm: 3.0
  learning_rate: 0.001

experiment_dir: 'experiments/smallrun64(conformer)_best/'




  