model_path: model.transformer.transformer
dataset: smartfallmm
model_args: 
  length : 128
  channels: 3
  num_heads: 4
  num_layers: 4
  embed_dim: 128
  dropout_rate: 0.25
  attention_dropout_rate: 0.25
  mlp_dim: 16


hyperparameters:
  batch_size: 64
  epochs: 120

dataset_args: 
  directory : datasets/smartfallmm/student_participants/accelerometer/watch_accelerometer
  train_subjects: [29,31,32,34,35,36,37,40]
  val_subjects: [41]
  window: 128
  stride: 10

optimizer_args: 
  global_clipnorm: 3.0
  amsgrad: 

experiment_dir: 'experiments/new_run/'




  